# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\"]\n\x0bSomeMessage\x12#\n\x06result\x18\x01 \x01(\x0b\x32\x13.SomeMessage.Result\x1a)\n\x06Result\x12\x0c\n\x04temp\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOMEMESSAGE._serialized_start=16
  _SOMEMESSAGE._serialized_end=109
  _SOMEMESSAGE_RESULT._serialized_start=68
  _SOMEMESSAGE_RESULT._serialized_end=109
# @@protoc_insertion_point(module_scope)
